version: 2
models:
 - name: dim_listings_cleansed
   columns:
    - name: listing_id
      description: Primary key for the listing
      tests:
       - unique
       - not_null
    - name: host_id
      description: The hosts's id. References the host table.
      tests:
       - not_null
    - name: room_type
      description: Type of the apartment / room
      